version: '3'

services:
  app:
    build: .
    depends_on:
      - postgres
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    volumes:
      - .:/app/
      - /app/node_modules
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
  migration:
    build:
      context: .
    command:
      [
        "./wait-for-it/wait-for-it.sh",
        "127.0.0.1:5432",
        "--",
        "npm",
        "run",
        "migrate"
      ]
    links:
      - postgres
    depends_on:
      - postgres
    env_file: ./.env
    environment:
      DB_HOST: postgres

  
